# Stage 1 - Build

FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o app .

# Stage 2: Runtime

FROM alpine:latest

WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder --chown=appuser:appgroup /app/app .

USER appuser

EXPOSE 8080

CMD ["./app"]
