# Stage 1 - Build

FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o app .

# Stage 2: Runtime

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/app .

EXPOSE 8080

CMD ["./app"]
